sudo: required
dist: trusty

matrix:
  include:
  - language: java
    jdk: oraclejdk8

script:
  - ./gradlew clean assemble --stacktrace
  - ./gradlew check --stacktrace

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
