on:
  push:
    branches:
      - main

jobs:
  steps:
    - uses: actions/checkout@v2
    - uses: bufbuild/buf-setup-action@v0.6.0
    - uses: bufbuild/buf-lint-action@v1
    - uses: bufbuild/buf-breaking-action@v1
      with:
        against: 'https://github.com/open-telemetry/opentelemetry-proto.git#branch=main,ref=HEAD~1'
    - uses: bufbuild/buf-push-action@v1
      with:
        buf_token: ${{ secrets.BUF_TOKEN }}