name: "Build language stubs"

on:
  push:
    branches:
      - master

jobs:
  build_java:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Generate Java soruce
        run: make gen-java
      - name: Build Java artifact
        uses: burrunan/gradle-cache-action@v1.5
        with:
          remote-build-cache-proxy-enabled: false
          build-root-directory: stubs/java
          arguments: build --stacktrace
